services:
  web:
    build: .
    ports:
      - "8080:80"     # Map port 80 in the container to port 8080 on your host
    volumes:
      - .:/var/www/html  # Useful in development for live changes; remove in production
    environment:
      # Define environment variables needed for your application (.env file can be used locally)
      - APP_ENV=production
      - DB_HOST=localhost
      - DB_NAME=room_vibe
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: room_vibe
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:



