<?php
require_once '../config/auth.php';
requireManagerLogin();

require_once '../../config/Database.php';
require_once '../../vendor/autoload.php';

use TCPDF as TCPDF;

if (!isset($_GET['id'])) {
    die("Booking ID not specified.");
}
$bookingId = $_GET['id'];

// Get the domain for QR code generation
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
$domain = $protocol . $_SERVER['HTTP_HOST'];
$viewReceiptUrl = $domain . "/room-vibe-backend/frontend/manager/pages/booking-details.php?id=" . $bookingId;

// Fetch booking details with extended information
$database = new Database();
$conn = $database->getConnection();

$stmt = $conn->prepare("
    SELECT 
        b.*,
        h.hostel_name, h.location, h.rating, h.accomodation_status,
        r.room_number, r.price, r.specification,
        rt.type_name as room_type,
        b.first_name, b.last_name, b.email, b.phone,
        s.gender, b.program, b.year_of_study
    FROM booking b
    JOIN hostel h ON b.hostel_id = h.id
    JOIN room r ON b.room_id = r.id
    JOIN room_types rt ON r.room_type_id = rt.room_type_id
    JOIN student s ON b.student_id = s.id
    WHERE b.id = ?
");
$stmt->execute([$bookingId]);
$booking = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$booking) {
    die("Booking not found.");
}

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('RoomVibe');
$pdf->SetAuthor('RoomVibe Management');
$pdf->SetTitle('Booking Details Report');

// Remove header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Add a page
$pdf->AddPage();

// Logo and Header
$logoPath = __DIR__ . '/../../images/room.png';
if (file_exists($logoPath)) {
    $pdf->Image($logoPath, 15, 15, 30);
}

// QR Code
$pdf->write2DBarcode($viewReceiptUrl, 'QRCODE,L', 150, 15, 30, 30);

// Header
$pdf->SetFont('helvetica', 'B', 20);
$pdf->SetY(30);
$pdf->Cell(0, 10, 'BOOKING DETAILS REPORT', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 10);
$pdf->Cell(0, 5, 'Report Generated: ' . date('j F Y'), 0, 1, 'C');

// Student Information
$pdf->Ln(10);
$pdf->SetFont('helvetica', 'B', 14);
$pdf->Cell(0, 10, 'Student Information', 0, 1, 'L');
$pdf->SetFont('helvetica', '', 10);

$studentInfo = '<table cellpadding="5">
    <tr><td width="30%"><b>Name:</b></td><td>' . $booking['first_name'] . ' ' . $booking['last_name'] . '</td></tr>
    <tr><td><b>Email:</b></td><td>' . $booking['email'] . '</td></tr>
    <tr><td><b>Phone:</b></td><td>' . $booking['phone'] . '</td></tr>
    <tr><td><b>Gender:</b></td><td>' . $booking['gender'] . '</td></tr>
    <tr><td><b>Program:</b></td><td>' . $booking['program'] . '</td></tr>
    <tr><td><b>Level:</b></td><td>' . $booking['year_of_study'] . '</td></tr>
</table>';
$pdf->writeHTML($studentInfo);

// Booking Information
$pdf->Ln(5);
$pdf->SetFont('helvetica', 'B', 14);
$pdf->Cell(0, 10, 'Booking Details', 0, 1, 'L');
$pdf->SetFont('helvetica', '', 10);

$bookingInfo = '<table cellpadding="5">
    <tr><td width="30%"><b>Booking ID:</b></td><td>#' . $booking['id'] . '</td></tr>
    <tr><td><b>Status:</b></td><td>' . ($booking['paid'] ? 'Paid' : 'Pending Payment') . '</td></tr>
    <tr><td><b>Amount:</b></td><td>GHS ' . number_format($booking['amount'], 2) . '</td></tr>
    <tr><td><b>Booking Date:</b></td><td>' . date('j F Y, g:i a', strtotime($booking['created_at'])) . '</td></tr>
</table>';
$pdf->writeHTML($bookingInfo);

// Room and Hostel Information
$pdf->Ln(5);
$pdf->SetFont('helvetica', 'B', 14);
$pdf->Cell(0, 10, 'Accommodation Details', 0, 1, 'L');
$pdf->SetFont('helvetica', '', 10);

$hostelInfo = '<table cellpadding="5">
    <tr><td width="30%"><b>Hostel:</b></td><td>' . $booking['hostel_name'] . '</td></tr>
    <tr><td><b>Location:</b></td><td>' . $booking['location'] . '</td></tr>
    <tr><td><b>Room Number:</b></td><td>' . $booking['room_number'] . '</td></tr>
    <tr><td><b>Room Type:</b></td><td>' . $booking['room_type'] . '</td></tr>
    <tr><td><b>Specification:</b></td><td>' . $booking['specification'] . '</td></tr>
</table>';
$pdf->writeHTML($hostelInfo);

// Footer
$pdf->SetY(-50);
$pdf->SetFont('helvetica', 'I', 8);
$pdf->Cell(0, 10, 'This is an official booking report generated by RoomVibe Management System.', 0, 1, 'C');
$pdf->Cell(0, 10, 'For verification, please scan the QR code above or contact the hostel management.', 0, 1, 'C');

// Output PDF
$pdf->Output('Booking_Report_' . $bookingId . '.pdf', 'I');