#Home
http://localhost:5000/
###

#Get all hostels
http://localhost:5000/hostels
###

#Get single hostel by ID
http://localhost:5000/hostel/2
###

#Create a new hostel
http://localhost:5000/hostel

{
    
}
###